/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecibosRouteImport } from './routes/_app.recibos'
import { Route as AppPreciosRouteImport } from './routes/_app.precios'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSolicitudesIndexRouteImport } from './routes/_app.solicitudes.index'
import { Route as AppRecibosIndexRouteImport } from './routes/_app.recibos.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppSolicitudesNuevaRouteImport } from './routes/_app.solicitudes.nueva'
import { Route as AppSolicitudesIdRouteImport } from './routes/_app.solicitudes.$id'
import { Route as AppRecibosUbicacionesRouteImport } from './routes/_app.recibos.ubicaciones'
import { Route as AppRecibosPreciosArticulosRouteImport } from './routes/_app.recibos.precios-articulos'
import { Route as AppRecibosNuevoRouteImport } from './routes/_app.recibos.nuevo'
import { Route as AppRecibosDerivacionesRouteImport } from './routes/_app.recibos.derivaciones'
import { Route as AppRecibosClientesRouteImport } from './routes/_app.recibos.clientes'
import { Route as AppRecibosCargarUbicacionRouteImport } from './routes/_app.recibos.cargar-ubicacion'
import { Route as AppClientesNuevoRouteImport } from './routes/_app.clientes.nuevo'
import { Route as AppAdminCreditosIndexRouteImport } from './routes/_app.admin.creditos.index'
import { Route as AppAdminCreditosIdRouteImport } from './routes/_app.admin.creditos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecibosRoute = AppRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AppRoute,
} as any)
const AppPreciosRoute = AppPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitudesIndexRoute = AppSolicitudesIndexRouteImport.update({
  id: '/solicitudes/',
  path: '/solicitudes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecibosIndexRoute = AppRecibosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecibosRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSolicitudesNuevaRoute = AppSolicitudesNuevaRouteImport.update({
  id: '/solicitudes/nueva',
  path: '/solicitudes/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitudesIdRoute = AppSolicitudesIdRouteImport.update({
  id: '/solicitudes/$id',
  path: '/solicitudes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecibosUbicacionesRoute = AppRecibosUbicacionesRouteImport.update({
  id: '/ubicaciones',
  path: '/ubicaciones',
  getParentRoute: () => AppRecibosRoute,
} as any)
const AppRecibosPreciosArticulosRoute =
  AppRecibosPreciosArticulosRouteImport.update({
    id: '/precios-articulos',
    path: '/precios-articulos',
    getParentRoute: () => AppRecibosRoute,
  } as any)
const AppRecibosNuevoRoute = AppRecibosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppRecibosRoute,
} as any)
const AppRecibosDerivacionesRoute = AppRecibosDerivacionesRouteImport.update({
  id: '/derivaciones',
  path: '/derivaciones',
  getParentRoute: () => AppRecibosRoute,
} as any)
const AppRecibosClientesRoute = AppRecibosClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRecibosRoute,
} as any)
const AppRecibosCargarUbicacionRoute =
  AppRecibosCargarUbicacionRouteImport.update({
    id: '/cargar-ubicacion',
    path: '/cargar-ubicacion',
    getParentRoute: () => AppRecibosRoute,
  } as any)
const AppClientesNuevoRoute = AppClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCreditosIndexRoute = AppAdminCreditosIndexRouteImport.update({
  id: '/creditos/',
  path: '/creditos/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCreditosIdRoute = AppAdminCreditosIdRouteImport.update({
  id: '/creditos/$id',
  path: '/creditos/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/precios': typeof AppPreciosRoute
  '/recibos': typeof AppRecibosRouteWithChildren
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/recibos/cargar-ubicacion': typeof AppRecibosCargarUbicacionRoute
  '/recibos/clientes': typeof AppRecibosClientesRoute
  '/recibos/derivaciones': typeof AppRecibosDerivacionesRoute
  '/recibos/nuevo': typeof AppRecibosNuevoRoute
  '/recibos/precios-articulos': typeof AppRecibosPreciosArticulosRoute
  '/recibos/ubicaciones': typeof AppRecibosUbicacionesRoute
  '/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/admin/': typeof AppAdminIndexRoute
  '/recibos/': typeof AppRecibosIndexRoute
  '/solicitudes/': typeof AppSolicitudesIndexRoute
  '/admin/creditos/$id': typeof AppAdminCreditosIdRoute
  '/admin/creditos/': typeof AppAdminCreditosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/precios': typeof AppPreciosRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/recibos/cargar-ubicacion': typeof AppRecibosCargarUbicacionRoute
  '/recibos/clientes': typeof AppRecibosClientesRoute
  '/recibos/derivaciones': typeof AppRecibosDerivacionesRoute
  '/recibos/nuevo': typeof AppRecibosNuevoRoute
  '/recibos/precios-articulos': typeof AppRecibosPreciosArticulosRoute
  '/recibos/ubicaciones': typeof AppRecibosUbicacionesRoute
  '/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/admin': typeof AppAdminIndexRoute
  '/recibos': typeof AppRecibosIndexRoute
  '/solicitudes': typeof AppSolicitudesIndexRoute
  '/admin/creditos/$id': typeof AppAdminCreditosIdRoute
  '/admin/creditos': typeof AppAdminCreditosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/precios': typeof AppPreciosRoute
  '/_app/recibos': typeof AppRecibosRouteWithChildren
  '/_app/clientes/nuevo': typeof AppClientesNuevoRoute
  '/_app/recibos/cargar-ubicacion': typeof AppRecibosCargarUbicacionRoute
  '/_app/recibos/clientes': typeof AppRecibosClientesRoute
  '/_app/recibos/derivaciones': typeof AppRecibosDerivacionesRoute
  '/_app/recibos/nuevo': typeof AppRecibosNuevoRoute
  '/_app/recibos/precios-articulos': typeof AppRecibosPreciosArticulosRoute
  '/_app/recibos/ubicaciones': typeof AppRecibosUbicacionesRoute
  '/_app/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/_app/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/recibos/': typeof AppRecibosIndexRoute
  '/_app/solicitudes/': typeof AppSolicitudesIndexRoute
  '/_app/admin/creditos/$id': typeof AppAdminCreditosIdRoute
  '/_app/admin/creditos/': typeof AppAdminCreditosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/perfil'
    | '/precios'
    | '/recibos'
    | '/clientes/nuevo'
    | '/recibos/cargar-ubicacion'
    | '/recibos/clientes'
    | '/recibos/derivaciones'
    | '/recibos/nuevo'
    | '/recibos/precios-articulos'
    | '/recibos/ubicaciones'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/admin/'
    | '/recibos/'
    | '/solicitudes/'
    | '/admin/creditos/$id'
    | '/admin/creditos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard'
    | '/perfil'
    | '/precios'
    | '/clientes/nuevo'
    | '/recibos/cargar-ubicacion'
    | '/recibos/clientes'
    | '/recibos/derivaciones'
    | '/recibos/nuevo'
    | '/recibos/precios-articulos'
    | '/recibos/ubicaciones'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/admin'
    | '/recibos'
    | '/solicitudes'
    | '/admin/creditos/$id'
    | '/admin/creditos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/perfil'
    | '/_app/precios'
    | '/_app/recibos'
    | '/_app/clientes/nuevo'
    | '/_app/recibos/cargar-ubicacion'
    | '/_app/recibos/clientes'
    | '/_app/recibos/derivaciones'
    | '/_app/recibos/nuevo'
    | '/_app/recibos/precios-articulos'
    | '/_app/recibos/ubicaciones'
    | '/_app/solicitudes/$id'
    | '/_app/solicitudes/nueva'
    | '/_app/admin/'
    | '/_app/recibos/'
    | '/_app/solicitudes/'
    | '/_app/admin/creditos/$id'
    | '/_app/admin/creditos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recibos': {
      id: '/_app/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof AppRecibosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/precios': {
      id: '/_app/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof AppPreciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitudes/': {
      id: '/_app/solicitudes/'
      path: '/solicitudes'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof AppSolicitudesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recibos/': {
      id: '/_app/recibos/'
      path: '/'
      fullPath: '/recibos/'
      preLoaderRoute: typeof AppRecibosIndexRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/solicitudes/nueva': {
      id: '/_app/solicitudes/nueva'
      path: '/solicitudes/nueva'
      fullPath: '/solicitudes/nueva'
      preLoaderRoute: typeof AppSolicitudesNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitudes/$id': {
      id: '/_app/solicitudes/$id'
      path: '/solicitudes/$id'
      fullPath: '/solicitudes/$id'
      preLoaderRoute: typeof AppSolicitudesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recibos/ubicaciones': {
      id: '/_app/recibos/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/recibos/ubicaciones'
      preLoaderRoute: typeof AppRecibosUbicacionesRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/recibos/precios-articulos': {
      id: '/_app/recibos/precios-articulos'
      path: '/precios-articulos'
      fullPath: '/recibos/precios-articulos'
      preLoaderRoute: typeof AppRecibosPreciosArticulosRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/recibos/nuevo': {
      id: '/_app/recibos/nuevo'
      path: '/nuevo'
      fullPath: '/recibos/nuevo'
      preLoaderRoute: typeof AppRecibosNuevoRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/recibos/derivaciones': {
      id: '/_app/recibos/derivaciones'
      path: '/derivaciones'
      fullPath: '/recibos/derivaciones'
      preLoaderRoute: typeof AppRecibosDerivacionesRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/recibos/clientes': {
      id: '/_app/recibos/clientes'
      path: '/clientes'
      fullPath: '/recibos/clientes'
      preLoaderRoute: typeof AppRecibosClientesRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/recibos/cargar-ubicacion': {
      id: '/_app/recibos/cargar-ubicacion'
      path: '/cargar-ubicacion'
      fullPath: '/recibos/cargar-ubicacion'
      preLoaderRoute: typeof AppRecibosCargarUbicacionRouteImport
      parentRoute: typeof AppRecibosRoute
    }
    '/_app/clientes/nuevo': {
      id: '/_app/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AppClientesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/creditos/': {
      id: '/_app/admin/creditos/'
      path: '/creditos'
      fullPath: '/admin/creditos/'
      preLoaderRoute: typeof AppAdminCreditosIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/creditos/$id': {
      id: '/_app/admin/creditos/$id'
      path: '/creditos/$id'
      fullPath: '/admin/creditos/$id'
      preLoaderRoute: typeof AppAdminCreditosIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminCreditosIdRoute: typeof AppAdminCreditosIdRoute
  AppAdminCreditosIndexRoute: typeof AppAdminCreditosIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminCreditosIdRoute: AppAdminCreditosIdRoute,
  AppAdminCreditosIndexRoute: AppAdminCreditosIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRecibosRouteChildren {
  AppRecibosCargarUbicacionRoute: typeof AppRecibosCargarUbicacionRoute
  AppRecibosClientesRoute: typeof AppRecibosClientesRoute
  AppRecibosDerivacionesRoute: typeof AppRecibosDerivacionesRoute
  AppRecibosNuevoRoute: typeof AppRecibosNuevoRoute
  AppRecibosPreciosArticulosRoute: typeof AppRecibosPreciosArticulosRoute
  AppRecibosUbicacionesRoute: typeof AppRecibosUbicacionesRoute
  AppRecibosIndexRoute: typeof AppRecibosIndexRoute
}

const AppRecibosRouteChildren: AppRecibosRouteChildren = {
  AppRecibosCargarUbicacionRoute: AppRecibosCargarUbicacionRoute,
  AppRecibosClientesRoute: AppRecibosClientesRoute,
  AppRecibosDerivacionesRoute: AppRecibosDerivacionesRoute,
  AppRecibosNuevoRoute: AppRecibosNuevoRoute,
  AppRecibosPreciosArticulosRoute: AppRecibosPreciosArticulosRoute,
  AppRecibosUbicacionesRoute: AppRecibosUbicacionesRoute,
  AppRecibosIndexRoute: AppRecibosIndexRoute,
}

const AppRecibosRouteWithChildren = AppRecibosRoute._addFileChildren(
  AppRecibosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPreciosRoute: typeof AppPreciosRoute
  AppRecibosRoute: typeof AppRecibosRouteWithChildren
  AppClientesNuevoRoute: typeof AppClientesNuevoRoute
  AppSolicitudesIdRoute: typeof AppSolicitudesIdRoute
  AppSolicitudesNuevaRoute: typeof AppSolicitudesNuevaRoute
  AppSolicitudesIndexRoute: typeof AppSolicitudesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPreciosRoute: AppPreciosRoute,
  AppRecibosRoute: AppRecibosRouteWithChildren,
  AppClientesNuevoRoute: AppClientesNuevoRoute,
  AppSolicitudesIdRoute: AppSolicitudesIdRoute,
  AppSolicitudesNuevaRoute: AppSolicitudesNuevaRoute,
  AppSolicitudesIndexRoute: AppSolicitudesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
