/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSolicitudesIndexRouteImport } from './routes/_app.solicitudes.index'
import { Route as AppSolicitudesNuevaRouteImport } from './routes/_app.solicitudes.nueva'
import { Route as AppSolicitudesIdRouteImport } from './routes/_app.solicitudes.$id'
import { Route as AppClientesNuevoRouteImport } from './routes/_app.clientes.nuevo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitudesIndexRoute = AppSolicitudesIndexRouteImport.update({
  id: '/solicitudes/',
  path: '/solicitudes/',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitudesNuevaRoute = AppSolicitudesNuevaRouteImport.update({
  id: '/solicitudes/nueva',
  path: '/solicitudes/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitudesIdRoute = AppSolicitudesIdRouteImport.update({
  id: '/solicitudes/$id',
  path: '/solicitudes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNuevoRoute = AppClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/solicitudes/': typeof AppSolicitudesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/perfil': typeof AppPerfilRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/solicitudes': typeof AppSolicitudesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/clientes/nuevo': typeof AppClientesNuevoRoute
  '/_app/solicitudes/$id': typeof AppSolicitudesIdRoute
  '/_app/solicitudes/nueva': typeof AppSolicitudesNuevaRoute
  '/_app/solicitudes/': typeof AppSolicitudesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard'
    | '/perfil'
    | '/clientes/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard'
    | '/perfil'
    | '/clientes/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/perfil'
    | '/_app/clientes/nuevo'
    | '/_app/solicitudes/$id'
    | '/_app/solicitudes/nueva'
    | '/_app/solicitudes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitudes/': {
      id: '/_app/solicitudes/'
      path: '/solicitudes'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof AppSolicitudesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitudes/nueva': {
      id: '/_app/solicitudes/nueva'
      path: '/solicitudes/nueva'
      fullPath: '/solicitudes/nueva'
      preLoaderRoute: typeof AppSolicitudesNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitudes/$id': {
      id: '/_app/solicitudes/$id'
      path: '/solicitudes/$id'
      fullPath: '/solicitudes/$id'
      preLoaderRoute: typeof AppSolicitudesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/nuevo': {
      id: '/_app/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AppClientesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppClientesNuevoRoute: typeof AppClientesNuevoRoute
  AppSolicitudesIdRoute: typeof AppSolicitudesIdRoute
  AppSolicitudesNuevaRoute: typeof AppSolicitudesNuevaRoute
  AppSolicitudesIndexRoute: typeof AppSolicitudesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppClientesNuevoRoute: AppClientesNuevoRoute,
  AppSolicitudesIdRoute: AppSolicitudesIdRoute,
  AppSolicitudesNuevaRoute: AppSolicitudesNuevaRoute,
  AppSolicitudesIndexRoute: AppSolicitudesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
